listening_port = 5000
database_uri = "postgresql://localhost:5432/registry"
app_settings = "production"

[db]
host = 'localhost'
port = 5432
name = 'registry'
datapath = '/var/local/pgsql/data/'

[superuser]
name = 'regdb'
group = 'regdb'
password = ''
