version: '3'
services:
  programs_registry:
    restart: always
    build: .
    volumes:
      - .:/programs_registry
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://regdb:@postgres:5432/registry
  postgres:
    restart: always
    image: postgres:9.6.6
    volumes: 
      - /var/lib/postgresql
      - 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=regdb
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=registry

