version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
    - DATABASE_URL
  database:
    image: "postgres"
