version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
  database:
    image: "postgres"
