version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    - APP_SETTINGS=production
    - FLASK_APP=app.py
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
