version: 2
jobs:
  build:
    working_directory: ~/programs_registry
    docker:
      - image: brighthive/python
      # For the database service
      - image: postgres:9.6.6
        environment:
        - POSTGRES_USER=regdb
        - POSTGRES_DB=registry
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.1-ce  # Latest verion
      - run: 
          name: Install required OS libs for psycopg
          command: apt-get -y install python-dev libpq-dev
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: Upgrade database, run tests and start server
          command: |
            python -m venv venv
            . venv/bin/activate
            export DATABASE_URL="postgres://regdb@localhost:5432/registry"
            export FLASK_ENV="development"
            export FLASK_APP="programs_registry"
            pip install -e .
            ./init.sh
            
# TODO: update the Heroku scripts if that's still used for CI
#      - run:
#          name: Install Docker client
#          command: |
#            if [ $CIRCLE_BRANCH = 'master' ] || [ $CIRCLE_BRANCH = 'develop' ]; then
#            set -x
#            VER="17.03.0-ce"
#            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
#            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#            mv /tmp/docker/* /usr/bin; fi
#      - run:
#          name: Install Heroku CLI
#          command: |
#            if [ $CIRCLE_BRANCH = 'master' ] || [ $CIRCLE_BRANCH = 'develop' ]; then wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh; fi
#      - run:
#          name: Deploy to Heroku
#          command: |
#            . venv/bin/activate
#            if [ $CIRCLE_BRANCH = 'master' ] || [ $CIRCLE_BRANCH = 'develop' ]; then sh heroku.sh; fi
